apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: 3scale-operator
spec:
  channel: ${OPERATOR_CHANNEL}
  installPlanApproval: Automatic
  name: 3scale-operator
  source: ${OPERATOR_SOURCE}
  sourceNamespace: openshift-marketplace
