# Copy this file under /config

settings:
  porta_dir: '~/workspace/porta'
  threescale_operator_dir: '~/workspace/3scale-operator'
  apisonator_env_file: '~/workspace/apisonator/.env'
  registry_secret_file_path: '~/.my-secrets/rh-registry-sa-secret.yaml'
  operator_channel: 'threescale-2.8'
  quay_repo: 'quay.io/username/3scale'
  cluster_domain: 'devel-openshift-cluster.com'
  aws_access_key_id: '<aws-access-key>'
  aws_secret_access_key: '<aws-secret-access-key>'
  aws_bucket: '<aws-bucket>'
  aws_region: '<aws-region>'
  apicast_registry_url: 'https://apicast-staging.proda.3sca.net/policies'
  dev_gtld: 'local'
