# Copy this file under /config

settings:
  porta:
    dir: '~/workspace/porta'
  zync:
    dir: '~/workspace/zync'
    env:
      DATABASE_URL: "postgresql://postgres:@localhost:5432/zync"
  sidekiq:
    prometheus_port: "9395"
  threescale_operator_dir: '~/workspace/3scale-operator'
  openshift_template: 'amp-eval'
  registry_secrets_glob: '~/.my-secrets/*.yaml'
  operator_channel: 'threescale-2.9'  # e.g. 'alpha', 'threescale-2.9'
  operator_source: 'redhat-operators' # e.g. 'threescale-productized-index-alpha', 'redhat-operators'
  quay_repo: 'quay.io/username/3scale'
  cluster_domain: 'devel-openshift-cluster.com'
  aws_access_key_id: '<aws-access-key>'
  aws_secret_access_key: '<aws-secret-access-key>'
  aws_bucket: '<aws-bucket>'
  aws_region: '<aws-region>'
  apicast_registry_url: 'https://policies.apicast.io/latest/policies.json'
