kind: Secret
apiVersion: v1
metadata:
  creationTimestamp: null
  name: aws-auth
stringData:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_BUCKET: ${AWS_BUCKET}
  AWS_REGION: ${AWS_REGION}
type: Opaque
