apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: 3scale-operator
spec:
  channel: ${OPERATOR_CHANNEL}
  name: 3scale-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
