kind: Secret
apiVersion: v1
metadata:
  creationTimestamp: null
  name: system-master-apicast
stringData:
  ACCESS_TOKEN: ${APICAST_SECRET}
  BASE_URL: http://${APICAST_SECRET}@system-master:3000
  PROXY_CONFIGS_ENDPOINT: http://${APICAST_SECRET}@system-master:3000/master/api/proxy/configs
type: Opaque
